### ISSUE TITLE
Matcher checks for 'available' offers, but provider creates 'open' offers

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/flocx-market#121]
It's possible that the issue should be fixed on the provider side.

**Comment by larsks** [comment]
This looks like another place where we should be validating input data. It also suggests that a `flocx-common` package that included an `OfferStatus` enumeration might be useful, so that rather than hardcoding strings into our code we could be using published constants in both the provider and the marketplace.

**Comment by tzumainn** [comment]
Will be fixed from the provider side: https://github.com/CCI-MOC/esi-leap/pull/10
